apiVersion: v1
kind: Service
metadata:
  labels:
    app: insurance-react-frontend
  name: insurance-react-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    app: insurance-react-frontend
  type: LoadBalancer 